sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        ZWAvS/R8K7chD+XRHvRapj1RcIdaX1B3sqOuYAVJPPzQDp7GjzwirQAgLaeW6bg3XWP0+K1iYFG830c7/Ufi9r8o9enLV7AcGoYTMwDFgKlm7J6u6I3uf68DRbfi+J9GD7owipuvTfw9VQzt0mxRGltDIoRsCfKW/h27lrk2bwt4jHLX6RmI731nRjSfgrj6lBoCoIJjKIppODhGog3QMKGpBedt3H3syZysp9aLgkh3woQDx4OpXmQQhmRTXdcEiBW6bTlXLqu6HjeodIOf6xkH8rRs3PrD3FuPuCISyqvY8PohEF8zSeLpP5wbHgEe+2/u7wWEu2pbuazxHWhcmStCEnQz6LwCmUU1tsmLjUfp8X1O2pyoUAhRYxIfkTbE0gBbab0NHrAU0lfbk9miEomSKayFNHmkwmaBUu+NUdUYEQmY9C/v0dYnPDBvbL26LZDYoGEX84T6brn3WN+4FyytDOWBl8eZNC0ubdU8ju9fhJ48BLbXvoOD0tb82y79DsPPIWVE/SqjrVjfg+Hqcnhv+cLRh4T8dcekWjdt9EAMAKE/zRTHaelvWd978zvjqicDlQUHIQ6nfYsPLt1+tDol3cdpiPrnf1tKjkgwfU/m3MIJWmAh76e7fpjOkUYKe6bVWBANMqfOQIWb6Xame/3OF2yfo7j9g8NyTQZkvaw=
    - secure: >-
        ObXE3qPDZd5AfC2ucG4x6SjICt1s3W1BV7sDthzPG3WUGfbuYYZFtmn3BHHrIKK1JvSqjB6gbw6E1mCcNoB7bE32CazzDLNsG59AD0ADdtskee+LwU67biOshDNx2cdSvgdR9lW8rPB7LNacw9InnsRzuRi0R10JI1TboBgM9isUOls2mX/f7R9jToJo34homeg9IXI8nqWHOkIuRmEN1pDUUpETkFt4acctmu6Tg0MbHatXEKiW6Boek+OrsT9n/L9q1W4Wd258yjxEcT0uHz/43yP/MXcMqDwItib8mPpAsv50I0X+nmu9lp5H0yTD46HRgf0FevI3rW+P5pCndovdGWk/UhsEelUWeRlYFSXEwVJ3rk0Az2GEdGeEzGEQXrcA4omShN0klKVaeRw3y81rYYNzOSUAPRm0mAM09DXyGjSZ3USXXsw2YqRkm7uRHI36Zc5I8D2AXEWMrm+y8hu/FB/xRIua7GYU8j9rYENOB65/4X4M0gDyKj275qU0EmZcIjFG5kICWCxrLbUDvQov70Lqh8Pew9wtouJ1BaLCPk3Mc+0wvf/64pP4+K+yb5hOI2nWaZlzMY09A1jTFZr476lJ2zexldgxZi6M/FGfz/+85yCRrCK7n/ee1snysaeILzqkEnY7HNiKoj70CbU+/1ev9SegyuGzpNexz4A=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
